// Code generated by binclude; DO NOT EDIT.

package config

import (
	"github.com/lu4p/binclude"
	"time"
)

var (
	_binclude0 = []byte("mongo:\r\n  host: 127.0.01\r\n  port: 27017\r\n  username: admin\r\n  password: pw123456\r\n\r\n# PROD为正式\r\nenv: DEV\r\njwt-key: WC7fkchY6FL6eS1")
	BinFS      = &binclude.FileSystem{Files: map[string]*binclude.File{"..": {Filename: "..", Mode: 2147484159, ModTime: time.Unix(1605256962, 662002100), Compression: binclude.None, Content: nil}, "../assets": {Filename: "assets", Mode: 2147484159, ModTime: time.Unix(1605256396, 200988200), Compression: binclude.None, Content: nil}, "../assets/config.yml": {Filename: "config.yml", Mode: 438, ModTime: time.Unix(1605256830, 659035100), Compression: binclude.None, Content: _binclude0}, "..\\assets": {Filename: "assets", Mode: 2147484159, ModTime: time.Unix(1605256962, 662002100), Compression: binclude.None, Content: nil}}}
)
